from django.db import models


# Create your models here.
class Hospital(models.Model):
    ProviderID = models.CharField(max_length =10, primary_key=True)
    MORT_30_AMI = models.FloatField(max_length=5, null= True, blank= True)
    MORT_30_HF = models.FloatField(max_length = 5, null= True, blank= True)
    MORT_30_PN = models.FloatField(max_length = 5, null= True, blank= True)
    PSI_90_SAFETY = models.FloatField(max_length = 5, null= True, blank= True)
    IMM_2 = models.FloatField(max_length = 5, null= True, blank= True)
    PN_6 = models.FloatField(max_length = 5, null= True, blank= True)
    SCIP_CARD_2 = models.FloatField(max_length = 5, null= True, blank= True)
    SCIP_INF_2 = models.FloatField(max_length = 5, null= True, blank= True)
    SCIP_INF_3 = models.FloatField(max_length = 5, null= True, blank= True)
    SCIP_INF_9 = models.FloatField(max_length =5, null= True, blank= True)
    SCIP_VTE_2 = models.FloatField(max_length = 5, null= True, blank= True)
    AMI_7A = models.FloatField(max_length = 5, null= True, blank= True)
    HAI1 = models.FloatField(max_length = 5, null= True, blank= True)
    HAI2 = models.FloatField(max_length = 5, null= True, blank= True)
    HAI3 = models.FloatField(max_length = 5, null= True, blank= True)
    HAI4 = models.FloatField(max_length = 5, null= True, blank= True)
    H_CLEAN_HSP_A_P = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_1_A_P = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_2_A_P = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_3_A_P = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_4_A_P = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_5_A_P = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_7_A = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_7_SA = models.FloatField(max_length = 5, null= True, blank= True)
    H_QUIET_HSP_A_P = models.FloatField(max_length = 5, null= True, blank= True)
    H_CLEAN_QUIET = models.FloatField(max_length = 5, null= True, blank= True)
    H_COMP_7 = models.FloatField(max_length = 5, null= True, blank= True)
    MSPB_1 = models.FloatField(max_length = 5, null= True, blank= True)

    HospitalName = models.CharField(max_length = 100, null= True, blank= True)
    Address = models.CharField(max_length = 200, null= True, blank= True)
    City = models.CharField(max_length = 20, null= True, blank= True)
    State = models.CharField(max_length = 20, null= True, blank= True)
    ZIPCode = models.CharField(max_length = 10, null= True, blank= True)
    CountyName = models.CharField(max_length = 50, null= True, blank= True)
    PhoneNumber = models.CharField(max_length = 15, null= True, blank= True)
    HospitalType = models.CharField(max_length = 50, null= True, blank= True)
    HospitalOwnership = models.CharField(max_length = 50, null= True, blank= True)
    EmergencyServices = models.CharField(max_length = 15, null= True, blank= True)